### Micro A

GET http://localhost:3000/api/v1/health/

###

GET http://localhost:3000/api/v1/version/


### Gateway Proxy

GET http://localhost:8080/version/
###

GET http://localhost:8080/health/

### Gateway LB

GET http://localhost:5000/api/v1/health/