### Micro A

GET http://localhost:3000/api/v1/health/

###

GET http://localhost:3000/api/v1/version/


### Gateway Proxy

GET http://localhost:8080/version/
###

GET http://localhost:8080/health/

### Gateway LB

GET http://localhost:3030/health/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCYW5rIiwic3ViIjoiU3lzdGVtQXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwIiwiZXhwIjoxNjI0ODk3ODQ4LCJuYmYiOjE2MjQ4OTkwNDgsImlhdCI6MTYyNDg5NzI0OCwianRpIjoiYXV0aC1zZXJ2ZXItMSIsIlVzZXJuYW1lIjoiTUFkbWluIiwiUm9sZSI6IkFETUlOIn0.TJn1Luy6jFsuRiQN0fAJYYQTxYWnO1wgWAUTGThY1Gg

### Proxy

GET http://localhost:5000/health/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCYW5rIiwic3ViIjoiU3lzdGVtQXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwIiwiZXhwIjoxNjI0ODk3ODQ4LCJuYmYiOjE2MjQ4OTkwNDgsImlhdCI6MTYyNDg5NzI0OCwianRpIjoiYXV0aC1zZXJ2ZXItMSIsIlVzZXJuYW1lIjoiTUFkbWluIiwiUm9sZSI6IkFETUlOIn0.TJn1Luy6jFsuRiQN0fAJYYQTxYWnO1wgWAUTGThY1Gg


###
GET http://localhost:5000/health/
X-API-KEY: 6fa741de1bdd1d91830ba