### Micro A

GET http://localhost:5000/api/v1/health/

###

GET http://localhost:5000/api/v1/version/


### Gateway Proxy

GET http://localhost:35000/health/
###


### Proxy
GET http://localhost:35000/version/
Authorization: Bearerx eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCYW5rIiwic3ViIjoiU3lzdGVtQXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwIiwiZXhwIjoxNjI0ODk3ODQ4LCJuYmYiOjE2MjQ4OTkwNDgsImlhdCI6MTYyNDg5NzI0OCwianRpIjoiYXV0aC1zZXJ2ZXItMSIsIlVzZXJuYW1lIjoiTUFkbWluIiwiUm9sZSI6IkFETUlOIn0.TJn1Luy6jFsuRiQN0fAJYYQTxYWnO1wgWAUTGThY1Gg

###
GET http://localhost:35000/version/
X-API-KEY: 6a1244e55eb42986b7c20742d29c04d74afa1b5b39d7e558c849c7e2141b1bf1


### Admin MNTG

GET http://localhost:10001/api/v1/mngt/